name: Deploy Menu Website

on:
  push:
    branches:
      - main  # 推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Push to gh-pages branch
        run: |
          # 创建 gh-pages 分支（如果不存在）
          git checkout -b gh-pages || true
          # 强制推送当前目录到 gh-pages 分支
          git add .
          git commit -m "Deploy to GitHub Pages" -a
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
